# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-09-06 06:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('df', '0003_auto_20200906_1413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppurchase',
            old_name='shop_name',
            new_name='name',
        ),
    ]
