# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-09-06 06:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('df', '0004_auto_20200906_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppurchase',
            name='name',
            field=models.ForeignKey(db_column='shop_name', on_delete=django.db.models.deletion.CASCADE, to='df.shops', verbose_name='商品名称'),
        ),
    ]
