# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-09-06 07:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('df', '0009_auto_20200906_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopput',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df.shops', verbose_name='入库商品'),
        ),

    ]
