# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-09-06 08:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('df', '0010_auto_20200906_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='shopout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outchase', models.IntegerField(default=0, verbose_name='出库数量')),
            ],
            options={
                'verbose_name': '出库管理',
                'verbose_name_plural': '出库管理',
                'db_table': 'shopout',
            },
        ),
        migrations.AlterField(
            model_name='shops',
            name='shop_number',
            field=models.IntegerField(default=0, verbose_name='商品数量'),
        ),
        migrations.AddField(
            model_name='shopout',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df.shops', verbose_name='出库商品'),
        ),
    ]
