# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-09-06 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df', '0011_auto_20200906_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopout',
            name='news_type',
            field=models.IntegerField(choices=[(1, '小程序出单'), (2, '淘宝出单'), (3, '线下出单')], default=1),
            preserve_default=False,
        ),
    ]
